# **ML 전처리&가공(Feature Engineering)**
* https://scikit-learn.org/stable/

* 결측 처리 : 빈값 채우기
* 이상치(Outlier) : 비정상 분포 데이터 (평균,최빈도,삭제)
* 인코딩 : 범주형 글자 -> 숫자  (남,여 -> 0,1  상,중,하->1,2,3)
* 파생피쳐 : 기존 피쳐로 의미있는 신규 피쳐 생성
* 차원축소 : 주성분 분석 (Principal Component Analysis, PCA)
* 정규화 : 데이터의 범위를 맞추는 작업 (스케일링, 규제)
    * 스케일링(로그변환) : 값의 범위 맞추기

# **[1] Data Load**

In [1]:
from sklearn import set_config
set_config(display="text")

In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split   #---- 문제답 분리
from sklearn.linear_model import LinearRegression      #---- 회귀모델
from sklearn.metrics import mean_squared_error         #---- 평가 메트릭스

In [3]:
df = pd.read_csv("../datas/BostonHousing.csv")
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [4]:
df.columns = df.columns.str.upper()

In [5]:
df.head(3)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7

# **[2] 문제지 답안지 분리**

```python
sklearn.model_selection.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)


wooriinjae.ai.vision.add(num1, num2)

## 문제지(X)

In [6]:
X = df.drop(columns=["MEDV"])
X.head(2)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.9,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.9,9.14

## 답안지(y)

In [7]:
y = df['MEDV']
y.head(2)

0    24.0
1    21.6
Name: MEDV, dtype: float64

## 문제지,답안지 분리(train_test_split)

In [8]:
X_train7, X_test3,    y_train7, y_test3 = train_test_split( X, y, test_size=0.3, random_state=1234)

In [9]:
X_train7.shape, X_test3.shape,    y_train7.shape, y_test3.shape

((354, 13), (152, 13), (354,), (152,))

# **[3] 공통함수**

In [22]:
def myscore(X_train7, y_train7, X_test3, y_test3) :
    lr = LinearRegression()  
    lr.fit(X_train7, y_train7)
    pred = lr.predict(X_test3)
    mse = mean_squared_error(y_test3, pred)
    print( f"mse : {np.sqrt(mse):.4f}" )

In [23]:
myscore(X_train7, y_train7, X_test3, y_test3)

mse : 4.9105

# **[4] 전처리&가공**

<pre>X 결측 처리 : 빈값 채우기
X 인코딩 : 범주형 글자 -> 숫자 (남,여 -> 0,1 상,중,하->1,2,3)

## 이상치(Outlier) : 비정상 분포 데이터 (평균,최빈도,삭제)

## 정규화 : 데이터의 범위를 맞추는 작업 (스케일링, 규제)

## 파생피쳐 : 기존 피쳐로 의미있는 신규 피쳐 생성

## 차원축소 : 주성분 분석 (Principal Component Analysis, PCA)